Algoritmo "EXERC CIRCULO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/5/2024
Var
// Seção de Declarações das variáveis 
   r, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do raio do circulo: ")
   leia(r)
   area <- PI * Exp(r,2)
   escreval("AREA = ", area:8:3)

Fimalgoritmo