Algoritmo "EXERC SOMA"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/5/2024
Var
// Seção de Declarações das variáveis 
  x, y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Digite o valor de X:")
  leia(x)
  escreva("Digite o valor de Y: ")
  leia(y)
  escreval("SOMA = ", x+y)

Fimalgoritmo