Algoritmo "EXERC SEQUECIA_IMPARES"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/5/2024
Var
// Seção de Declarações das variáveis 
  x, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor de X: ")
   leia(x)
   
   para i de 1 ate x faca
   se i % 2 <> 0 entao
   escreval(i)
   fimse
   fimpara
Fimalgoritmo